let a = 10;
let b = 0;

try {
    let c;
    c = a / b;
    console.log(c);
}
catch (err) {
    console.log(err);
}